### ISSUE TITLE
[CRASH] Server crashing when loading chunk with a modified mob by Eldritch

### ISSUE THREAD

**Issue by ghost** [HyperPigeon/Eldritch-Mobs#61] opened 2022-07-30 15:38 UTC
Hello there,

Here's the crash report :
[crash-2022-07-30_17.35.44-server.txt](https://github.com/HyperPigeon/Eldritch-Mobs/files/9226817/crash-2022-07-30_17.35.44-server.txt)

I don't know how to fix it, and dunno if it's a compatibility issue... Thanks in advance

**Comment by TelepathicGrunt** [comment] 2022-09-19 23:52
Another user reported a similar crash also caused by an unsafe cast in Eldritch Mobs.
https://mclo.gs/qfWUPTf

Here’s the code that’s the issue. This is checking if the player is a PlayerEntity but not a ServerPlayerEntity. So this is doing an unsafe cast to ServerPlayerEntity without actually checking if the player is an actual ServerPlayerEntity.
https://github.com/HyperPigeon/Eldritch-Mobs/blob/b32e1367b0227629f5520661c353b2fc5fb66f26/src/main/java/net/hyper_pigeon/eldritch_mobs/ability/active/offensive/GravityAbility.java#L69

changing these similar if statements throughout the mod from `instanceof PlayerEntity` to `instanceof ServerPlayerEntity` should stop these casting crashes for good

**Comment by HyperPigeon** [comment] 2022-11-13 21:51
Fixed in the latest release for 1.18.2.

**Closed as completed by HyperPigeon** 2022-11-13 21:51 UTC
