### ISSUE TITLE
incompatibilities with other mods

### ISSUE THREAD

**Issue by sldains** [HyperPigeon/Eldritch-Mobs#22] opened 2021-03-06 02:50 UTC
Is there any way I can make this mod play better with other mods that add new mobs to the game? I really like this mod but I keep getting issues where if I'm running this mod and add another mod that adds new mobs, then I get a glitch where all entities become invisible.

**Comment by HyperPigeon** [comment] 2021-04-29 02:14
Is it possible for you to provide some pictures or other form of documentation that lets me get a clearer idea of what the issue is?

**Comment by HyperPigeon** [comment] 2021-05-23 20:37
This page on the Minecraft wiki may prove useful to you: https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack

The invisible entity glitch should also be fixed in the latest release. 

If you still have trouble adding new mobs to the list of allowed mobs, make another issue on this GitHub page and I'll do my best to explain the process to you.

**Closed by HyperPigeon** 2021-05-23 20:37 UTC
